name: build
on:
  push:
    branches:
      - development/*
env:
  branch: ${{vars.BRANCHNAME}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: config node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: checkout development
        uses: actions/checkout@v4
        with:
          token: ${{secrets.TOKEN}}
      
      - name: install dependencies
        run: npm i
      
      - name: build site
        run: npm artro build
      
      - name: save change
        run: |
              git config user.name ${{vars.USERNAME}}
              git config user.email ${{vars.EMAIL_ACTOR}}
              git add .
              git commit -m "building app"
              git checkout main
              git merge ${{env.branch}}
              git pull origin main

     

